# V1 pipeline RAG

## Analyse des besoins et cadre de travail :
- **Cible** : Chercheurs, historiens, archivistes, étudiants en histoire.
- **Cas d'usage** : Recherche d’informations historiques, génération de résumé
- **Types de données** : Articles de journaux historiques, images, métadonnées.
- **Langues** : Français, Anglais
- **Dataset** : Miracl

## Téléchargement des blibliothèques et modèles

In [ ]:
!pip install datasets
!pip install dateparser

!pip install -U pip setuptools wheel
!pip install -U 'spacy[cuda12x]'
!python -m spacy download fr_core_news_sm
!pip install sentence-transformers[onnx-gpu]
!pip install pinecone

Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (3.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.12.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.30.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.19.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: dateparser in /usr/local/lib/python3.11/dist-packages (1.2.1)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.11/dist-packages (from dateparser) (2.8.2)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.11/dist-packages (from dateparser) (2025.2)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27,>=2015.06.24 in /usr/local/lib/python3.11/dist-packages (from dateparser) (2024.11.6)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.11/dist-packages (from dateparser) (5.3.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7.0->dateparser) (1.17.0)
Requirement already satisfied: pip in /usr/local/lib/python3.11/dist-packages (25.0.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (79.0.0)
Requirement already satisfied: wheel in /usr/local/lib/python3.11/dist-packages (0.45.1)
Requirement already satisfied: spacy[cuda12x] in /usr/local/lib/python3.11/dist-packages (3.8.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (8.3.4)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (0.15.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (2.11.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (79.0.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (3.5.0)
Requirement already satisfied: cupy-cuda12x<13.0.0,>=11.5.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda12x]) (12.3.0)
Requirement already satisfied: fastrlock>=0.5 in /usr/local/lib/python3.11/dist-packages (from cupy-cuda12x<13.0.0,>=11.5.0->spacy[cuda12x]) (0.8.3)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy[cuda12x]) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda12x]) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda12x]) (2.33.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda12x]) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda12x]) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda12x]) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda12x]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda12x]) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda12x]) (2025.1.31)
Requirement already satisfied: blis<1.3.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy[cuda12x]) (1.2.1)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy[cuda12x]) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy[cuda12x]) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy[cuda12x]) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy[cuda12x]) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy[cuda12x]) (0.21.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy[cuda12x]) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy[cuda12x]) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy[cuda12x]) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[cuda12x]) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[cuda12x]) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy[cuda12x]) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[cuda12x]) (0.1.2)
Collecting fr-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-3.8.0/fr_core_news_sm-3.8.0-py3-none-any.whl (16.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 100.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('fr_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Requirement already satisfied: sentence-transformers[onnx-gpu] in /usr/local/lib/python3.11/dist-packages (3.4.1)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers[onnx-gpu]) (4.48.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence-transformers[onnx-gpu]) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers[onnx-gpu]) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers[onnx-gpu]) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers[onnx-gpu]) (1.14.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers[onnx-gpu]) (0.30.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers[onnx-gpu]) (11.1.0)
Requirement already satisfied: optimum>=1.23.1 in /usr/local/lib/python3.11/dist-packages (from optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (1.24.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers[onnx-gpu]) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers[onnx-gpu]) (2024.12.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers[onnx-gpu]) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers[onnx-gpu]) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers[onnx-gpu]) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers[onnx-gpu]) (4.13.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optimum>=1.23.1->optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (1.26.4)
Requirement already satisfied: onnx in /usr/local/lib/python3.11/dist-packages (from optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (1.17.0)
Requirement already satisfied: onnxruntime-gpu>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (1.21.1)
Requirement already satisfied: datasets>=1.2.1 in /usr/local/lib/python3.11/dist-packages (from optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (3.5.0)
Requirement already satisfied: evaluate in /usr/local/lib/python3.11/dist-packages (from optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (0.4.3)
Requirement already satisfied: protobuf>=3.20.1 in /usr/local/lib/python3.11/dist-packages (from optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (5.29.4)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers[onnx-gpu]) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers[onnx-gpu]) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers[onnx-gpu]) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers[onnx-gpu]) (0.21.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers[onnx-gpu]) (0.5.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers[onnx-gpu]) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers[onnx-gpu]) (3.6.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=1.2.1->optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=1.2.1->optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets>=1.2.1->optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets>=1.2.1->optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets>=1.2.1->optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (0.70.16)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=1.2.1->optimum[onnxruntime-gpu]>=1.23.1; extra == "onnx-gpu"->sentence-transformers[onnx-gpu]) (3.11.15)

## Import des bibliothèques

In [ ]:
# Prétraitement
import datasets
from datasets import load_dataset
import pandas as pd
from itertools import islice
import re
import dateparser
from dateparser.search import search_dates
import datetime
import spacy
import numpy as np
from joblib import Parallel, delayed

# Embedding et Vectorisation
from sentence_transformers import SentenceTransformer

# Indexation
from pinecone import Pinecone, ServerlessSpec
from tqdm import tqdm
from google.colab import userdata
from concurrent.futures import ThreadPoolExecutor

## Prétraitement des données :

### Extraction du contenu brut
1. Téléchargement du dataset
2. Nettoyage du texte brut (suppression des balises HTML, des caractères spéciaux, en-têtes, pieds de page, etc.)

In [ ]:
languages = ['fr', 'en']
max_docs_per_lang = 100000 # taille du dataset (x2 car français + anglais)
all_docs = []

In [ ]:
def load_lang(lang, max_docs):
    print(f"[{lang.upper()}] Chargement...")
    dataset_stream = load_dataset('miracl/miracl-corpus', lang, split='train', streaming=True, trust_remote_code=True)
    sample = islice(dataset_stream, max_docs)

    docs = []
    for doc in sample:
        docs.append({
            "docid": doc["docid"],
            "lang": lang,
            "title": doc["title"],
            "text": doc["text"]
        })
    return docs

In [ ]:
results = Parallel(n_jobs=len(languages))(
    delayed(load_lang)(lang, max_docs_per_lang) for lang in languages
)
all_docs = [doc for lang_docs in results for doc in lang_docs]

In [ ]:
df = pd.DataFrame(all_docs)

In [ ]:
df.head()

,docid,lang,title,text
0,3#0,fr,Antoine Meillet,"Paul Jules Antoine Meillet, né le à Moulins (A..."
1,3#1,fr,Antoine Meillet,"D'origine bourbonnaise, fils d'un notaire de C..."
2,3#2,fr,Antoine Meillet,Étudiant à la faculté des lettres de Paris à p...
3,3#3,fr,Antoine Meillet,"En 1889, il est major de l'agrégation de gramm..."
4,3#4,fr,Antoine Meillet,Il assure à la suite de Saussure le cours de g...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   docid   200000 non-null  object
 1   lang    200000 non-null  object
 2   title   200000 non-null  object
 3   text    200000 non-null  object
dtypes: object(4)
memory usage: 6.1+ MB

In [ ]:
def clean_text(text):
  text = re.sub(r"<[^>]+>", "", text)  # Supprimer les balises HTML
  # text = re.sub(r"[^\w\s,.?!]", "", text)  # Supprimer caractères spéciaux
  text = re.sub(r"\s+", " ", text)  # Supprimer espaces multiples
  return text.strip()

In [ ]:
df["title"] = df["title"].apply(clean_text)
df["text"] = df["text"].apply(clean_text)

In [ ]:
df.describe()

          docid    lang       title          text
count    200000  200000      200000        200000
unique   180951       2        6123        198239
top     5288#19      fr  Strasbourg  Et aussi aux
freq          2  100000         423           178

### Segmentation des articles
1. Chunking sémantique (Déjà fait par le corpus)
2. Limitation de la taille des chunks (512 tokens)
3. Ajout de métadonnées (date, titre, auteur, etc.)

In [ ]:
# chunk_size = 512 # Pas besoin ici
chunk_text = []
chunk_meta = []

In [ ]:
for index, row in df.iterrows():
    text = row["text"]
    title = row["title"]
    docid = row["docid"]
    lang = row["lang"]
    sentences = text.split(". ")

    for sentence in sentences:
        chunk_text.append(sentence)
        chunk_meta.append({
            "title": title,
            "docid": docid,
            "lang": lang
        })

### Nettoyage et normalisation
1. Suppression des doublons
2. Normalisation des dates
3. Vérification de la langue

In [ ]:
print(len(chunk_text))
print(len(chunk_meta))

675198
675198

In [ ]:
# Suppression des doublons
df_chunk = pd.DataFrame({"text": chunk_text, "meta": chunk_meta})
df_chunk = df_chunk.drop_duplicates(subset=["text"])

In [ ]:
# Normalisation des dates dans le text
def extract_dates(text, lang):
    results = search_dates(text, languages=[lang], settings={'STRICT_PARSING': True})
    if not results:
        return [], None, None

    iso_dates = []
    for _, date in results:
        try:
            iso_dates.append(date.date().isoformat())
        except Exception:
            continue

    # Trier et déterminer min/max
    iso_dates = sorted(set(iso_dates))
    earliest = min(iso_dates) if iso_dates else None
    latest = max(iso_dates) if iso_dates else None

    return iso_dates, earliest, latest

In [ ]:
def enrich_meta_with_dates(row):
    iso_dates, earliest, latest = extract_dates(row["text"], row["meta"]["lang"])
    meta = row["meta"].copy() if isinstance(row["meta"], dict) else {}

    meta["dates_iso"] = iso_dates
    meta["earliest_date"] = earliest
    meta["latest_date"] = latest
    return meta

In [ ]:
def parallel_enrich_meta(df_chunk, n_jobs=-1):
    rows = df_chunk.to_dict(orient="records")

    metas = Parallel(n_jobs=8)(
      delayed(enrich_meta_with_dates)(row) for row in tqdm(rows)
    )

    df_chunk["meta"] = metas
    return df_chunk

In [ ]:
df_chunk = parallel_enrich_meta(df_chunk, n_jobs=32)

  0%|          | 0/667270 [00:00<?, ?it/s]
  0%|          | 1/667270 [00:00<103:32:19,  1.79it/s]
  0%|          | 8/667270 [00:03<72:34:29,  2.55it/s]
  0%|          | 16/667270 [00:03<35:03:31,  5.29it/s]
  0%|          | 96/667270 [00:03<3:54:08, 47.49it/s]
  0%|          | 512/667270 [00:03<33:04, 335.96it/s]
  0%|          | 1024/667270 [00:03<14:23, 771.24it/s]
  0%|          | 2048/667270 [00:04<06:37, 1673.33it/s]
  1%|          | 4096/667270 [00:04<03:16, 3377.80it/s]
  1%|          | 5120/667270 [00:04<02:57, 3721.51it/s]
  1%|          | 6144/667270 [00:04<02:54, 3785.30it/s]
  1%|          | 7168/667270 [00:05<02:37, 4182.58it/s]
  1%|          | 8192/667270 [00:05<02:27, 4454.92it/s]
  1%|▏         | 9216/667270 [00:05<02:32, 4306.26it/s]
  2%|▏         | 10240/667270 [00:05<02:19, 4717.32it/s]
  2%|▏         | 11264/667270 [00:05<02:10, 5041.88it/s]
  2%|▏         | 12288/667270 [00:06<02:02, 5340.63it/s]
  2%|▏         | 13312/667270 [00:06<01:59, 5481.01it/s]
  2%|▏         | 14336/667270 [00:06<02:01, 5369.66it/s]
  2%|▏         | 15360/667270 [00:06<02:04, 5251.02it/s]
  2%|▏         | 16384/667270 [00:06<02:04, 5223.29it/s]
  3%|▎         | 17408/667270 [00:06<01:56, 5564.91it/s]
  3%|▎         | 18432/667270 [00:07<01:55, 5595.82it/s]
  3%|▎         | 19456/667270 [00:07<01:56, 5567.84it/s]
  3%|▎         | 20480/667270 [00:07<01:53, 5692.18it/s]
  3%|▎         | 21504/667270 [00:07<01:48, 5937.96it/s]
  3%|▎         | 22528/667270 [00:07<01:52, 5731.03it/s]
  4%|▎         | 23552/667270 [00:07<01:50, 5804.34it/s]
  4%|▎         | 24576/667270 [00:08<01:57, 5471.41it/s]
  4%|▍         | 25600/667270 [00:08<01:57, 5478.66it/s]
  4%|▍         | 26624/667270 [00:08<02:00, 5327.95it/s]
  4%|▍         | 27648/667270 [00:08<02:00, 5294.60it/s]
  4%|▍         | 28672/667270 [00:08<01:58, 5406.53it/s]
  4%|▍         | 29696/667270 [00:09<01:50, 5760.43it/s]
  5%|▍         | 30720/667270 [00:09<01:53, 5602.30it/s]
  5%|▍         | 31744/667270 [00:09<02:01, 5244.51it/s]
  5%|▍         | 32768/667270 [00:09<02:02, 5184.31it/s]
  5%|▌         | 33792/667270 [00:09<02:01, 5202.07it/s]
  5%|▌         | 34816/667270 [00:10<01:53, 5579.13it/s]
  5%|▌         | 35840/667270 [00:10<01:54, 5527.51it/s]
  6%|▌         | 36864/667270 [00:10<01:44, 6016.39it/s]
  6%|▌         | 37888/667270 [00:10<01:55, 5433.57it/s]
  6%|▌         | 38912/667270 [00:10<01:55, 5424.54it/s]
  6%|▌         | 39936/667270 [00:11<02:00, 5187.56it/s]
  6%|▌         | 40960/667270 [00:11<01:48, 5798.85it/s]
  6%|▋         | 41984/667270 [00:11<01:51, 5624.16it/s]
  6%|▋         | 43008/667270 [00:11<01:50, 5663.02it/s]
  7%|▋         | 44032/667270 [00:11<01:50, 5640.67it/s]
  7%|▋         | 45056/667270 [00:11<01:52, 5541.90it/s]
  7%|▋         | 46080/667270 [00:12<01:51, 5582.28it/s]
  7%|▋         | 47104/667270 [00:12<01:49, 5675.66it/s]
  7%|▋         | 48128/667270 [00:12<01:51, 5558.53it/s]
  7%|▋         | 49152/667270 [00:12<01:56, 5311.88it/s]
  8%|▊         | 50176/667270 [00:12<01:44, 5931.88it/s]
  8%|▊         | 51200/667270 [00:12<01:43, 5931.46it/s]
  8%|▊         | 52224/667270 [00:13<01:54, 5383.64it/s]
  8%|▊         | 53248/667270 [00:13<01:47, 5696.50it/s]
  8%|▊         | 54272/667270 [00:13<01:48, 5639.72it/s]
  8%|▊         | 55296/667270 [00:13<01:45, 5784.08it/s]
  8%|▊         | 56320/667270 [00:13<01:53, 5398.15it/s]
  9%|▊         | 57344/667270 [00:14<01:43, 5892.89it/s]
  9%|▊         | 58368/667270 [00:14<01:35, 6376.49it/s]
  9%|▉         | 59392/667270 [00:14<01:52, 5392.45it/s]
  9%|▉         | 60416/667270 [00:14<01:47, 5660.94it/s]
  9%|▉         | 61440/667270 [00:14<01:44, 5804.16it/s]
  9%|▉         | 62464/667270 [00:15<01:50, 5488.89it/s]
 10%|▉         | 63488/667270 [00:15<01:54, 5274.64it/s]
 10%|▉         | 64512/667270 [00:15<01:47, 5622.84it/s]
 10%|▉         | 65536/667270 [00:15<01:48, 5570.53it/s]
 10%|▉         | 66560/667270 [00:15<01:56, 5175.14it/s]
 10%|█         | 67584/667270 [00:15<01:52, 5347.73it/s]
 10%|█         | 68608/667270 [00:16<02:03, 4860.72it/s]
 10%|█         | 69632/667270 [00:16<02:11, 4535.48it/s]
 11%|█         | 70656/667270 [00:16<02:25, 4091.20it/s]
 11%|█         | 71680/667270 [00:17<02:23, 4139.75it/s]
 11%|█         | 72704/667270 [00:17<02:19, 4262.22it/s]
 11%|█         | 73728/667270 [00:17<02:17, 4328.97it/s]
 11%|█         | 74752/667270 [00:17<02:02, 4829.57it/s]
 11%|█▏        | 75776/667270 [00:17<02:01, 4858.51it/s]
 12%|█▏        | 76800/667270 [00:18<02:05, 4716.99it/s]
 12%|█▏        | 77824/667270 [00:18<02:04, 4731.26it/s]
 12%|█▏        | 78848/667270 [00:18<02:00, 4895.72it/s]
 12%|█▏        | 79872/667270 [00:18<01:46, 5539.68it/s]
 12%|█▏        | 80896/667270 [00:18<01:41, 5772.48it/s]
 12%|█▏        | 81920/667270 [00:18<01:48, 5405.64it/s]
 12%|█▏        | 82944/667270 [00:19<01:53, 5140.24it/s]
 13%|█▎        | 83968/667270 [00:19<01:53, 5161.19it/s]
 13%|█▎        | 84992/667270 [00:19<01:53, 5119.48it/s]
 13%|█▎        | 86016/667270 [00:19<01:48, 5341.12it/s]
 13%|█▎        | 87040/667270 [00:20<01:52, 5148.08it/s]
 13%|█▎        | 88064/667270 [00:20<01:45, 5471.13it/s]
 13%|█▎        | 89088/667270 [00:20<01:43, 5559.88it/s]
 14%|█▎        | 90112/667270 [00:20<01:46, 5400.49it/s]
 14%|█▎        | 91136/667270 [00:20<01:45, 5486.91it/s]
 14%|█▍        | 92160/667270 [00:20<01:47, 5367.56it/s]
 14%|█▍        | 93184/667270 [00:21<01:39, 5743.56it/s]
 14%|█▍        | 94208/667270 [00:21<01:39, 5778.74it/s]
 14%|█▍        | 95232/667270 [00:21<01:45, 5404.88it/s]
 14%|█▍        | 96256/667270 [00:21<01:45, 5414.85it/s]
 15%|█▍        | 97280/667270 [00:21<01:50, 5151.63it/s]
 15%|█▍        | 98304/667270 [00:22<01:46, 5339.99it/s]
 15%|█▍        | 99328/667270 [00:22<01:37, 5846.73it/s]
 15%|█▌        | 100352/667270 [00:22<01:38, 5767.04it/s]
 15%|█▌        | 101376/667270 [00:22<01:33, 6067.25it/s]
 15%|█▌        | 102400/667270 [00:22<01:34, 5993.72it/s]
 15%|█▌        | 103424/667270 [00:22<01:33, 6047.85it/s]
 16%|█▌        | 104448/667270 [00:23<01:37, 5775.20it/s]
 16%|█▌        | 105472/667270 [00:23<01:37, 5736.39it/s]
 16%|█▌        | 106496/667270 [00:23<01:32, 6056.32it/s]
 16%|█▌        | 107520/667270 [00:23<01:29, 6234.92it/s]
 16%|█▋        | 108544/667270 [00:23<01:33, 5984.88it/s]
 16%|█▋        | 109568/667270 [00:23<01:36, 5790.75it/s]
 17%|█▋        | 110592/667270 [00:24<01:42, 5443.03it/s]
 17%|█▋        | 111616/667270 [00:24<01:29, 6202.15it/s]
 17%|█▋        | 112640/667270 [00:24<01:34, 5880.56it/s]
 17%|█▋        | 113664/667270 [00:24<01:39, 5546.72it/s]
 17%|█▋        | 114688/667270 [00:24<01:47, 5157.42it/s]
 17%|█▋        | 115712/667270 [00:25<01:37, 5645.40it/s]
 17%|█▋        | 116736/667270 [00:25<01:40, 5451.03it/s]
 18%|█▊        | 117760/667270 [00:25<01:32, 5950.62it/s]
 18%|█▊        | 118784/667270 [00:25<01:33, 5893.57it/s]
 18%|█▊        | 119808/667270 [00:25<01:32, 5900.89it/s]
 18%|█▊        | 120832/667270 [00:25<01:25, 6375.38it/s]
 18%|█▊        | 121856/667270 [00:26<01:32, 5926.83it/s]
 18%|█▊        | 122880/667270 [00:26<01:38, 5502.89it/s]
 19%|█▊        | 123904/667270 [00:26<01:28, 6129.11it/s]
 19%|█▊        | 124928/667270 [00:26<01:33, 5790.95it/s]
 19%|█▉        | 125952/667270 [00:26<01:27, 6203.19it/s]
 19%|█▉        | 126976/667270 [00:26<01:29, 6008.18it/s]
 19%|█▉        | 128000/667270 [00:27<01:28, 6107.64it/s]
 19%|█▉        | 129024/667270 [00:27<01:24, 6358.22it/s]
 19%|█▉        | 130048/667270 [00:27<01:30, 5957.77it/s]
 20%|█▉        | 131072/667270 [00:27<01:35, 5599.91it/s]
 20%|█▉        | 132096/667270 [00:27<01:38, 5455.80it/s]
 20%|█▉        | 133120/667270 [00:27<01:30, 5886.60it/s]
 20%|██        | 134144/667270 [00:28<01:34, 5629.44it/s]
 20%|██        | 135168/667270 [00:28<01:42, 5182.81it/s]
 20%|██        | 136192/667270 [00:28<01:47, 4951.02it/s]
 21%|██        | 137216/667270 [00:28<01:45, 5024.36it/s]
 21%|██        | 138240/667270 [00:29<01:49, 4830.10it/s]
 21%|██        | 139264/667270 [00:29<01:38, 5387.30it/s]
 21%|██        | 140288/667270 [00:29<01:45, 4976.43it/s]
 21%|██        | 141312/667270 [00:29<01:46, 4939.72it/s]
 21%|██▏       | 142336/667270 [00:29<01:34, 5539.66it/s]
 21%|██▏       | 143360/667270 [00:29<01:36, 5427.90it/s]
 22%|██▏       | 144384/667270 [00:30<01:46, 4903.37it/s]
 22%|██▏       | 145408/667270 [00:30<01:41, 5148.05it/s]
 22%|██▏       | 146432/667270 [00:30<01:44, 4977.76it/s]
 22%|██▏       | 147456/667270 [00:30<01:38, 5281.97it/s]
 22%|██▏       | 148480/667270 [00:30<01:33, 5538.62it/s]
 22%|██▏       | 149504/667270 [00:31<01:38, 5262.81it/s]
 23%|██▎       | 150528/667270 [00:31<01:34, 5465.74it/s]
 23%|██▎       | 151552/667270 [00:31<01:33, 5516.51it/s]
 23%|██▎       | 152576/667270 [00:31<01:29, 5782.37it/s]
 23%|██▎       | 153600/667270 [00:31<01:26, 5965.58it/s]
 23%|██▎       | 154624/667270 [00:32<01:26, 5924.18it/s]
 23%|██▎       | 155648/667270 [00:32<01:39, 5166.97it/s]
 23%|██▎       | 156672/667270 [00:32<01:35, 5319.77it/s]
 24%|██▎       | 157696/667270 [00:32<01:41, 5031.17it/s]
 24%|██▍       | 158720/667270 [00:32<01:37, 5231.74it/s]
 24%|██▍       | 159744/667270 [00:32<01:25, 5938.61it/s]
 24%|██▍       | 160768/667270 [00:33<01:23, 6057.25it/s]
 24%|██▍       | 161792/667270 [00:33<01:28, 5725.53it/s]
 24%|██▍       | 162816/667270 [00:33<01:28, 5693.83it/s]
 25%|██▍       | 163840/667270 [00:33<01:22, 6101.50it/s]
 25%|██▍       | 164864/667270 [00:33<01:23, 5995.06it/s]
 25%|██▍       | 165888/667270 [00:34<01:24, 5904.40it/s]
 25%|██▌       | 166912/667270 [00:34<01:25, 5833.76it/s]
 25%|██▌       | 167936/667270 [00:34<01:26, 5793.53it/s]
 25%|██▌       | 168960/667270 [00:34<01:25, 5817.04it/s]
 25%|██▌       | 169984/667270 [00:34<01:39, 4978.15it/s]
 26%|██▌       | 171008/667270 [00:34<01:31, 5405.96it/s]
 26%|██▌       | 172032/667270 [00:35<01:27, 5640.80it/s]
 26%|██▌       | 173056/667270 [00:35<01:24, 5855.19it/s]
 26%|██▌       | 174080/667270 [00:35<01:30, 5455.56it/s]
 26%|██▌       | 175104/667270 [00:35<01:22, 5983.93it/s]
 26%|██▋       | 176128/667270 [00:35<01:16, 6436.99it/s]
 27%|██▋       | 177152/667270 [00:35<01:23, 5845.47it/s]
 27%|██▋       | 178176/667270 [00:36<01:28, 5542.26it/s]
 27%|██▋       | 179200/667270 [00:36<01:23, 5829.44it/s]
 27%|██▋       | 180224/667270 [00:36<01:26, 5614.60it/s]
 27%|██▋       | 181248/667270 [00:36<01:23, 5849.76it/s]
 27%|██▋       | 182272/667270 [00:36<01:25, 5695.42it/s]
 27%|██▋       | 183296/667270 [00:37<01:28, 5449.31it/s]
 28%|██▊       | 184320/667270 [00:37<01:32, 5241.96it/s]
 28%|██▊       | 185344/667270 [00:37<01:26, 5584.60it/s]
 28%|██▊       | 186368/667270 [00:37<01:28, 5441.02it/s]
 28%|██▊       | 187392/667270 [00:37<01:33, 5149.75it/s]
 28%|██▊       | 188416/667270 [00:38<01:26, 5513.42it/s]
 28%|██▊       | 189440/667270 [00:38<01:28, 5392.39it/s]
 29%|██▊       | 190464/667270 [00:38<01:27, 5451.43it/s]
 29%|██▊       | 191488/667270 [00:38<01:22, 5765.53it/s]
 29%|██▉       | 192512/667270 [00:38<01:19, 5935.00it/s]
 29%|██▉       | 193536/667270 [00:39<01:31, 5197.34it/s]
 29%|██▉       | 194560/667270 [00:39<01:23, 5642.72it/s]
 29%|██▉       | 195584/667270 [00:39<01:27, 5363.36it/s]
 29%|██▉       | 196608/667270 [00:39<01:23, 5655.14it/s]
 30%|██▉       | 197632/667270 [00:39<01:24, 5545.74it/s]
 30%|██▉       | 198656/667270 [00:39<01:23, 5587.73it/s]
 30%|██▉       | 199680/667270 [00:40<01:28, 5312.35it/s]
 30%|███       | 200704/667270 [00:40<01:21, 5741.11it/s]
 30%|███       | 201728/667270 [00:40<01:33, 4959.24it/s]
 30%|███       | 202752/667270 [00:40<01:29, 5183.36it/s]
 31%|███       | 203776/667270 [00:40<01:28, 5219.27it/s]
 31%|███       | 204800/667270 [00:41<01:31, 5074.35it/s]
 31%|███       | 205824/667270 [00:41<01:39, 4651.03it/s]
 31%|███       | 206848/667270 [00:41<01:28, 5199.16it/s]
 31%|███       | 207872/667270 [00:41<01:24, 5433.97it/s]
 31%|███▏      | 208896/667270 [00:41<01:34, 4847.46it/s]
 31%|███▏      | 209920/667270 [00:42<01:33, 4868.09it/s]
 32%|███▏      | 210944/667270 [00:42<01:30, 5052.22it/s]
 32%|███▏      | 211968/667270 [00:42<01:29, 5084.38it/s]
 32%|███▏      | 212992/667270 [00:42<01:38, 4598.52it/s]
 32%|███▏      | 214016/667270 [00:42<01:31, 4942.11it/s]
 32%|███▏      | 215040/667270 [00:43<01:24, 5381.08it/s]
 32%|███▏      | 216064/667270 [00:43<01:29, 5025.65it/s]
 33%|███▎      | 217088/667270 [00:43<01:21, 5502.27it/s]
 33%|███▎      | 218112/667270 [00:43<01:25, 5254.17it/s]
 33%|███▎      | 219136/667270 [00:43<01:23, 5335.18it/s]
 33%|███▎      | 220160/667270 [00:44<01:28, 5046.08it/s]
 33%|███▎      | 221184/667270 [00:44<01:32, 4844.29it/s]
 33%|███▎      | 222208/667270 [00:44<01:27, 5075.34it/s]
 33%|███▎      | 223232/667270 [00:45<02:17, 3239.22it/s]
 34%|███▎      | 224256/667270 [00:45<02:23, 3076.85it/s]
 34%|███▍      | 225280/667270 [00:45<02:13, 3311.13it/s]
 34%|███▍      | 226304/667270 [00:45<01:49, 4036.25it/s]
 34%|███▍      | 227328/667270 [00:46<01:46, 4112.92it/s]
 34%|███▍      | 228352/667270 [00:46<01:37, 4516.34it/s]
 34%|███▍      | 229376/667270 [00:46<01:27, 4976.12it/s]
 35%|███▍      | 230400/667270 [00:46<01:26, 5070.21it/s]
 35%|███▍      | 231424/667270 [00:46<01:18, 5559.86it/s]
 35%|███▍      | 232448/667270 [00:47<01:24, 5123.20it/s]
 35%|███▍      | 233472/667270 [00:47<01:20, 5363.72it/s]
 35%|███▌      | 234496/667270 [00:47<01:14, 5818.07it/s]
 35%|███▌      | 235520/667270 [00:47<01:18, 5495.60it/s]
 35%|███▌      | 236544/667270 [00:47<01:18, 5460.89it/s]
 36%|███▌      | 237568/667270 [00:47<01:18, 5454.09it/s]
 36%|███▌      | 238592/667270 [00:48<01:15, 5683.28it/s]
 36%|███▌      | 239616/667270 [00:48<01:26, 4969.46it/s]
 36%|███▌      | 240640/667270 [00:48<01:24, 5035.87it/s]
 36%|███▌      | 241664/667270 [00:48<01:20, 5302.94it/s]
 36%|███▋      | 242688/667270 [00:48<01:21, 5225.17it/s]
 37%|███▋      | 243712/667270 [00:49<01:17, 5454.74it/s]
 37%|███▋      | 244736/667270 [00:49<01:13, 5781.34it/s]
 37%|███▋      | 245760/667270 [00:49<01:06, 6296.18it/s]
 37%|███▋      | 246784/667270 [00:49<01:16, 5467.43it/s]
 37%|███▋      | 247808/667270 [00:49<01:20, 5234.12it/s]
 37%|███▋      | 248832/667270 [00:50<01:17, 5409.88it/s]
 37%|███▋      | 249856/667270 [00:50<01:15, 5508.15it/s]
 38%|███▊      | 250880/667270 [00:50<01:15, 5481.62it/s]
 38%|███▊      | 251904/667270 [00:50<01:17, 5375.39it/s]
 38%|███▊      | 252928/667270 [00:50<01:17, 5318.43it/s]
 38%|███▊      | 253952/667270 [00:50<01:10, 5886.06it/s]
 38%|███▊      | 254976/667270 [00:51<01:03, 6463.46it/s]
 38%|███▊      | 256000/667270 [00:51<01:12, 5675.26it/s]
 39%|███▊      | 257024/667270 [00:51<01:04, 6401.91it/s]
 39%|███▊      | 258048/667270 [00:51<01:00, 6763.24it/s]
 39%|███▉      | 259072/667270 [00:51<01:11, 5738.46it/s]
 39%|███▉      | 260096/667270 [00:51<01:10, 5816.38it/s]
 39%|███▉      | 261120/667270 [00:52<01:10, 5735.21it/s]
 39%|███▉      | 262144/667270 [00:52<01:19, 5123.05it/s]
 39%|███▉      | 263168/667270 [00:52<01:18, 5156.18it/s]
 40%|███▉      | 264192/667270 [00:52<01:12, 5531.93it/s]
 40%|███▉      | 265216/667270 [00:52<01:11, 5613.42it/s]
 40%|███▉      | 266240/667270 [00:53<01:15, 5291.18it/s]
 40%|████      | 267264/667270 [00:53<01:17, 5194.17it/s]
 40%|████      | 268288/667270 [00:53<01:18, 5092.41it/s]
 40%|████      | 269312/667270 [00:53<01:44, 3809.85it/s]
 41%|████      | 270336/667270 [00:54<01:34, 4184.94it/s]
 41%|████      | 271360/667270 [00:54<01:27, 4549.68it/s]
 41%|████      | 272384/667270 [00:54<01:36, 4110.96it/s]
 41%|████      | 273408/667270 [00:54<01:21, 4809.54it/s]
 41%|████      | 274432/667270 [00:54<01:11, 5476.30it/s]
 41%|████▏     | 275456/667270 [00:55<01:13, 5356.93it/s]
 41%|████▏     | 276480/667270 [00:55<01:13, 5329.28it/s]
 42%|████▏     | 277504/667270 [00:55<01:05, 5938.46it/s]
 42%|████▏     | 278528/667270 [00:55<01:08, 5704.35it/s]
 42%|████▏     | 279552/667270 [00:55<01:14, 5175.34it/s]
 42%|████▏     | 280576/667270 [00:55<01:06, 5809.33it/s]
 42%|████▏     | 281600/667270 [00:56<01:01, 6264.44it/s]
 42%|████▏     | 282624/667270 [00:56<01:03, 6068.88it/s]
 43%|████▎     | 283648/667270 [00:56<01:01, 6211.61it/s]
 43%|████▎     | 284672/667270 [00:56<01:00, 6282.45it/s]
 43%|████▎     | 285696/667270 [00:56<00:59, 6464.20it/s]
 43%|████▎     | 286720/667270 [00:56<01:03, 5972.86it/s]
 43%|████▎     | 287744/667270 [00:57<01:03, 5990.36it/s]
 43%|████▎     | 288768/667270 [00:57<01:00, 6205.05it/s]
 43%|████▎     | 289792/667270 [00:57<01:05, 5804.60it/s]
 44%|████▎     | 290816/667270 [00:57<01:02, 6063.71it/s]
 44%|████▎     | 291840/667270 [00:57<01:03, 5933.42it/s]
 44%|████▍     | 292864/667270 [00:57<00:56, 6589.87it/s]
 44%|████▍     | 293888/667270 [00:58<01:09, 5406.32it/s]
 44%|████▍     | 294912/667270 [00:58<01:07, 5552.70it/s]
 44%|████▍     | 295936/667270 [00:58<01:08, 5395.36it/s]
 45%|████▍     | 296960/667270 [00:58<01:01, 6046.50it/s]
 45%|████▍     | 297984/667270 [00:58<00:58, 6353.91it/s]
 45%|████▍     | 299008/667270 [00:59<01:04, 5738.93it/s]
 45%|████▍     | 300032/667270 [00:59<01:00, 6111.24it/s]
 45%|████▌     | 301056/667270 [00:59<00:59, 6164.48it/s]
 45%|████▌     | 302080/667270 [00:59<00:59, 6133.45it/s]
 45%|████▌     | 303104/667270 [00:59<01:01, 5954.47it/s]
 46%|████▌     | 304128/667270 [00:59<00:58, 6204.04it/s]
 46%|████▌     | 305152/667270 [00:59<00:57, 6313.95it/s]
 46%|████▌     | 306176/667270 [01:00<00:58, 6203.33it/s]
 46%|████▌     | 307200/667270 [01:00<00:58, 6107.76it/s]
 46%|████▌     | 308224/667270 [01:00<01:07, 5299.15it/s]
 46%|████▋     | 309248/667270 [01:00<01:06, 5422.69it/s]
 46%|████▋     | 310272/667270 [01:00<01:04, 5526.35it/s]
 47%|████▋     | 311296/667270 [01:01<01:02, 5697.24it/s]
 47%|████▋     | 312320/667270 [01:01<01:05, 5379.51it/s]
 47%|████▋     | 313344/667270 [01:01<00:58, 6049.42it/s]
 47%|████▋     | 314368/667270 [01:01<01:03, 5549.00it/s]
 47%|████▋     | 315392/667270 [01:01<01:00, 5801.14it/s]
 47%|████▋     | 316416/667270 [01:01<00:59, 5934.22it/s]
 48%|████▊     | 317440/667270 [01:02<00:58, 6024.63it/s]
 48%|████▊     | 318464/667270 [01:02<01:08, 5102.58it/s]
 48%|████▊     | 319488/667270 [01:02<01:08, 5098.13it/s]
 48%|████▊     | 320512/667270 [01:02<01:09, 5002.85it/s]
 48%|████▊     | 321536/667270 [01:03<01:09, 4989.93it/s]
 48%|████▊     | 322560/667270 [01:03<01:08, 5041.62it/s]
 48%|████▊     | 323584/667270 [01:03<01:03, 5418.89it/s]
 49%|████▊     | 324608/667270 [01:03<00:57, 5947.52it/s]
 49%|████▉     | 325632/667270 [01:03<00:57, 5964.58it/s]
 49%|████▉     | 326656/667270 [01:03<01:01, 5542.19it/s]
 49%|████▉     | 327680/667270 [01:04<00:56, 5965.21it/s]
 49%|████▉     | 328704/667270 [01:04<01:02, 5401.69it/s]
 49%|████▉     | 329728/667270 [01:04<01:01, 5457.60it/s]
 50%|████▉     | 330752/667270 [01:04<01:00, 5554.76it/s]
 50%|████▉     | 331776/667270 [01:04<00:59, 5652.96it/s]
 50%|████▉     | 332800/667270 [01:05<01:03, 5247.17it/s]
 50%|█████     | 333824/667270 [01:05<01:06, 5002.28it/s]
 50%|█████     | 334848/667270 [01:05<01:14, 4433.74it/s]
 50%|█████     | 335872/667270 [01:05<01:17, 4288.89it/s]
 50%|█████     | 336896/667270 [01:06<01:13, 4478.48it/s]
 51%|█████     | 337920/667270 [01:06<01:06, 4950.65it/s]
 51%|█████     | 338944/667270 [01:06<01:03, 5143.16it/s]
 51%|█████     | 339968/667270 [01:06<01:01, 5359.97it/s]
 51%|█████     | 340992/667270 [01:06<00:54, 5987.05it/s]
 51%|█████▏    | 342016/667270 [01:06<00:50, 6483.88it/s]
 51%|█████▏    | 343040/667270 [01:07<00:59, 5467.41it/s]
 52%|█████▏    | 344064/667270 [01:07<00:56, 5702.63it/s]
 52%|█████▏    | 345088/667270 [01:07<00:56, 5750.90it/s]
 52%|█████▏    | 346112/667270 [01:07<01:00, 5267.30it/s]
 52%|█████▏    | 347136/667270 [01:07<00:56, 5650.53it/s]
 52%|█████▏    | 348160/667270 [01:07<00:53, 5927.57it/s]
 52%|█████▏    | 349184/667270 [01:08<00:50, 6305.80it/s]
 52%|█████▏    | 350208/667270 [01:08<00:52, 6019.23it/s]

In [ ]:
df_chunk.head() # Amélioration possible avec les dates (uniquement année)

,text,meta
0,"Paul Jules Antoine Meillet, né le à Moulins Al...","{'title': 'Antoine Meillet', 'docid': '3#0', '..."
1,Il est aussi philologue.,"{'title': 'Antoine Meillet', 'docid': '3#0', '..."
2,"Dorigine bourbonnaise, fils dun notaire de Châ...","{'title': 'Antoine Meillet', 'docid': '3#1', '..."
3,Étudiant à la faculté des lettres de Paris à p...,"{'title': 'Antoine Meillet', 'docid': '3#2', '..."
4,"En 1889, il est major de lagrégation de gramma...","{'title': 'Antoine Meillet', 'docid': '3#3', '..."

### Reconnaissance des éntités nommées :

In [ ]:
nlp_fr = spacy.load("fr_core_news_sm", disable=["tagger", "parser"])
nlp_en = spacy.load("en_core_web_sm", disable=["tagger", "parser"])

In [ ]:
def enrich_df_with_ner_pipe(df_chunk): # À AMÉLIORER
    enriched_rows = []

    for lang in ["fr", "en"]:
        sub_df = df_chunk[df_chunk["meta"].apply(lambda m: m.get("lang") == lang)]
        if sub_df.empty:
            continue

        nlp = get_nlp(lang)
        texts = sub_df["text"].tolist()
        metas = sub_df["meta"].tolist()

        docs = list(nlp.pipe(texts, batch_size=256))

        for meta, doc in zip(metas, docs):
            entities = [{"text": ent.text, "label": ent.label_} for ent in doc.ents]
            meta = meta.copy()
            meta["entities"] = entities
            enriched_rows.append({"text": doc.text, "meta": meta})

    return pd.DataFrame(enriched_rows)

In [ ]:
chunks = np.array_split(df_chunk, 64)

/usr/local/lib/python3.11/dist-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [ ]:
_nlp_models = {}

def get_nlp(lang):
    if lang not in _nlp_models:
        _nlp_models[lang] = spacy.load(
            "fr_core_news_sm" if lang == "fr" else "en_core_web_sm",
            disable=["tagger", "parser"]
        )
    return _nlp_models[lang]

In [ ]:
results = Parallel(n_jobs=8, backend="loky", prefer="processes")(
    delayed(enrich_df_with_ner_pipe)(chunk) for chunk in tqdm(chunks)
)

  0%|          | 0/64 [00:00<?, ?it/s]
 25%|██▌       | 16/64 [00:54<02:42,  3.38s/it]/usr/local/lib/python3.11/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

 38%|███▊      | 24/64 [01:55<03:27,  5.19s/it]
 50%|█████     | 32/64 [02:50<03:04,  5.78s/it]
 62%|██████▎   | 40/64 [03:41<02:24,  6.00s/it]
 75%|███████▌  | 48/64 [04:11<01:24,  5.28s/it]
 88%|████████▊ | 56/64 [04:40<00:37,  4.73s/it]
100%|██████████| 64/64 [05:13<00:00,  4.90s/it]

In [ ]:
df = pd.concat(results, ignore_index=True)

In [ ]:
df_chunk = df
df_chunk.head()

,text,meta
0,"Paul Jules Antoine Meillet, né le à Moulins Al...","{'title': 'Antoine Meillet', 'docid': '3#0', '..."
1,Il est aussi philologue.,"{'title': 'Antoine Meillet', 'docid': '3#0', '..."
2,"Dorigine bourbonnaise, fils dun notaire de Châ...","{'title': 'Antoine Meillet', 'docid': '3#1', '..."
3,Étudiant à la faculté des lettres de Paris à p...,"{'title': 'Antoine Meillet', 'docid': '3#2', '..."
4,"En 1889, il est major de lagrégation de gramma...","{'title': 'Antoine Meillet', 'docid': '3#3', '..."

## Embedding et Vectorisation :

### Choix du modèle d'embedding
1. [gte-Qwen2-1.5B-instruct](https://huggingface.co/Alibaba-NLP/gte-Qwen2-1.5B-instruct) -> Trop gros
2. [e5-small-v2](https://huggingface.co/intfloat/e5-small-v2)

In [ ]:
embedding_model = SentenceTransformer("intfloat/e5-small-v2", trust_remote_code=True, backend="onnx")

WARNING:sentence_transformers.models.Transformer:No 'model.onnx' found in 'intfloat/e5-small-v2'. Exporting the model to ONNX.
WARNING:sentence_transformers.models.Transformer:If you intended to load one of the ['onnx/model_O4.onnx', 'onnx/model_qint8_avx512_vnni.onnx'] ONNX files, please specify the desired file name via `model_kwargs={"file_name": "onnx/model_O4.onnx"}`.

*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:505 void onnxruntime::python::RegisterTensorRTPluginsAsCustomOps(PySessionOptions&, const onnxruntime::ProviderOptions&) Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************

WARNING:sentence_transformers.models.Transformer:Saving the exported ONNX model is heavily recommended to avoid having to export it again. Do so with `model.push_to_hub('intfloat/e5-small-v2', create_pr=True)`.

### Vectorisation des chunks
1. Transformation des chunks en vecteurs d'embedding

In [ ]:
df["chunk"] = df["meta"].apply(lambda m: m.get("title", "")) + "\n" + df["text"]

In [ ]:
texts = df["chunk"].tolist()

In [ ]:
embeddings = embedding_model.encode(
    texts,
    batch_size=256,
    show_progress_bar=True,
    normalize_embeddings=True
)

Batches:   0%|          | 0/2607 [00:00<?, ?it/s]

### Sauvegarde des vecteurs

In [ ]:
np_embeddings = np.array(embeddings)
np.save("embeddings.npy", np_embeddings)

In [ ]:
len(embeddings)

667270

## Indexation

In [ ]:
embeddings = np.load("embeddings.npy")

### Création de la base de donnée vectorielle

In [ ]:
pc = Pinecone(api_key=userdata.get("PINECONE"))

In [ ]:
index_name = "rag-v1"

if not pc.has_index(index_name):
    pc.create_index(
        name=index_name,
        dimension=embeddings.shape[1],
        metric="cosine",
        spec=ServerlessSpec(
            cloud="aws",
            region="us-east-1"
        )
    )

In [ ]:
index = pc.Index(index_name)

### Création du set de donnée

Chaque entrée a :
- un identifiant
- un vecteur
- le text d'origine
- les éléments de métadonnée

In [ ]:
def format_for_pinecone(i, row, embedding):
    meta = row["meta"]
    return (
        str(i),
        embedding.astype("float32").tolist(),
        {
            "title": meta["title"],
            "lang": meta["lang"],
            "year": meta["earliest_date"][:4] if meta["earliest_date"] else "",
            "entities": [ent["text"] for ent in meta.get("entities", [])][:5]
        }
    )

In [ ]:
pinecone_data_parallel = Parallel(n_jobs=-1)(
    delayed(format_for_pinecone)(i, row, embeddings[i])
    for i, row in tqdm(enumerate(df_chunk.to_dict(orient="records")), total=len(df_chunk))
)

  0%|          | 0/667270 [00:00<?, ?it/s]

  0%|          | 12/667270 [00:05<87:23:52,  2.12it/s]

  0%|          | 96/667270 [00:05<8:10:21, 22.68it/s]

  0%|          | 768/667270 [00:05<44:41, 248.52it/s]

  0%|          | 2304/667270 [00:05<11:48, 938.50it/s]

  1%|          | 4608/667270 [00:06<04:51, 2270.67it/s]

  1%|          | 7771/667270 [00:06<02:23, 4606.69it/s]

  1%|▏         | 9602/667270 [00:06<01:50, 5951.65it/s]

  2%|▏         | 12288/667270 [00:06<01:19, 8192.39it/s]

  3%|▎         | 18432/667270 [00:06<00:47, 13796.02it/s]

  4%|▎         | 24576/667270 [00:06<00:38, 16807.09it/s]

  5%|▍         | 30720/667270 [00:07<00:37, 16930.46it/s]

  6%|▌         | 36864/667270 [00:07<00:37, 17034.47it/s]

  6%|▋         | 43008/667270 [00:08<00:36, 17048.28it/s]

  7%|▋         | 49152/667270 [00:08<00:36, 17156.42it/s]

  8%|▊         | 55296/667270 [00:08<00:35, 17251.90it/s]

  9%|▉         | 61440/667270 [00:09<00:34, 17364.77it/s]

 10%|█         | 67584/667270 [00:09<00:34, 17372.35it/s]

 11%|█         | 73728/667270 [00:09<00:34, 17137.78it/s]

 12%|█▏        | 79872/667270 [00:10<00:34, 17200.67it/s]

 13%|█▎        | 86016/667270 [00:10<00:34, 16985.67it/s]

 14%|█▍        | 92160/667270 [00:10<00:33, 17036.35it/s]

 15%|█▍        | 98304/667270 [00:11<00:33, 16961.21it/s]

 16%|█▌        | 104448/667270 [00:11<00:33, 17034.86it/s]

 17%|█▋        | 110592/667270 [00:11<00:32, 17218.94it/s]

 17%|█▋        | 116736/667270 [00:12<00:31, 17261.80it/s]

 18%|█▊        | 122880/667270 [00:12<00:31, 17288.10it/s]

 19%|█▉        | 129024/667270 [00:13<00:31, 17295.12it/s]

 20%|██        | 135168/667270 [00:13<00:30, 17388.27it/s]

 21%|██        | 141312/667270 [00:13<00:30, 17477.19it/s]

 22%|██▏       | 147456/667270 [00:14<00:29, 17413.53it/s]

 23%|██▎       | 153600/667270 [00:14<00:29, 17488.36it/s]

 24%|██▍       | 159744/667270 [00:14<00:29, 17298.00it/s]

 25%|██▍       | 165888/667270 [00:15<00:28, 17312.86it/s]

 26%|██▌       | 172032/667270 [00:15<00:28, 17332.91it/s]

 27%|██▋       | 178176/667270 [00:15<00:28, 17156.85it/s]

 28%|██▊       | 184320/667270 [00:16<00:28, 17161.49it/s]

 29%|██▊       | 190464/667270 [00:16<00:27, 17276.90it/s]

 29%|██▉       | 196608/667270 [00:16<00:27, 17222.34it/s]

 30%|███       | 202752/667270 [00:17<00:26, 17328.23it/s]

 31%|███▏      | 208896/667270 [00:17<00:26, 17438.02it/s]

 32%|███▏      | 215040/667270 [00:17<00:26, 17273.92it/s]

 33%|███▎      | 221184/667270 [00:18<00:26, 17150.61it/s]

 34%|███▍      | 227328/667270 [00:18<00:25, 16923.40it/s]

 35%|███▍      | 233472/667270 [00:19<00:26, 16532.61it/s]

 36%|███▌      | 239616/667270 [00:19<00:26, 16193.75it/s]

 37%|███▋      | 245760/667270 [00:19<00:25, 16362.12it/s]

 38%|███▊      | 251904/667270 [00:20<00:25, 16404.09it/s]

 39%|███▊      | 258048/667270 [00:20<00:24, 16569.82it/s]

 40%|███▉      | 264192/667270 [00:20<00:24, 16794.22it/s]

 41%|████      | 270336/667270 [00:21<00:23, 16673.64it/s]

 41%|████▏     | 276480/667270 [00:21<00:23, 16595.77it/s]

 42%|████▏     | 282624/667270 [00:22<00:23, 16430.54it/s]

 43%|████▎     | 288768/667270 [00:22<00:24, 15503.67it/s]

 44%|████▍     | 294912/667270 [00:23<00:25, 14585.83it/s]

 45%|████▌     | 301056/667270 [00:23<00:25, 14521.14it/s]

 46%|████▌     | 307200/667270 [00:23<00:24, 14850.07it/s]

 47%|████▋     | 313344/667270 [00:24<00:23, 15304.51it/s]

 48%|████▊     | 319488/667270 [00:24<00:23, 14994.76it/s]

 49%|████▉     | 325632/667270 [00:24<00:21, 15803.87it/s]

 50%|████▉     | 331776/667270 [00:25<00:20, 16181.62it/s]

 51%|█████     | 337920/667270 [00:25<00:19, 16651.37it/s]

 52%|█████▏    | 344064/667270 [00:26<00:20, 15931.82it/s]

 52%|█████▏    | 350208/667270 [00:26<00:19, 15943.88it/s]

 53%|█████▎    | 356352/667270 [00:26<00:18, 16445.55it/s]

 54%|█████▍    | 362496/667270 [00:27<00:18, 16656.92it/s]

 55%|█████▌    | 368640/667270 [00:27<00:17, 16973.60it/s]

 56%|█████▌    | 374784/667270 [00:27<00:16, 17259.45it/s]

 57%|█████▋    | 380928/667270 [00:28<00:16, 17392.39it/s]

 58%|█████▊    | 387072/667270 [00:28<00:16, 17340.96it/s]

 59%|█████▉    | 393216/667270 [00:28<00:15, 17280.91it/s]

 60%|█████▉    | 399360/667270 [00:29<00:15, 17302.72it/s]

 61%|██████    | 405504/667270 [00:29<00:15, 17354.51it/s]

 62%|██████▏   | 411648/667270 [00:30<00:14, 17323.08it/s]

 63%|██████▎   | 417792/667270 [00:30<00:14, 17382.37it/s]

 64%|██████▎   | 423936/667270 [00:30<00:13, 17496.85it/s]

 64%|██████▍   | 430080/667270 [00:31<00:13, 17649.74it/s]

 65%|██████▌   | 436224/667270 [00:31<00:12, 17929.89it/s]

 66%|██████▋   | 442368/667270 [00:31<00:12, 17601.90it/s]

 67%|██████▋   | 448512/667270 [00:32<00:12, 17517.51it/s]

 68%|██████▊   | 454656/667270 [00:32<00:12, 17708.35it/s]

 69%|██████▉   | 460800/667270 [00:32<00:11, 17403.72it/s]

 70%|██████▉   | 466944/667270 [00:33<00:11, 17480.44it/s]

 71%|███████   | 473088/667270 [00:33<00:11, 17364.35it/s]

 72%|███████▏  | 479232/667270 [00:33<00:10, 17297.33it/s]

 73%|███████▎  | 485376/667270 [00:34<00:10, 17242.57it/s]

 74%|███████▎  | 491520/667270 [00:34<00:10, 17207.88it/s]

 75%|███████▍  | 497664/667270 [00:34<00:10, 16939.30it/s]

 76%|███████▌  | 503808/667270 [00:35<00:09, 17056.56it/s]

 76%|███████▋  | 509952/667270 [00:35<00:09, 16973.29it/s]

 77%|███████▋  | 516096/667270 [00:36<00:08, 17204.79it/s]

 78%|███████▊  | 522240/667270 [00:36<00:08, 17112.50it/s]

 79%|███████▉  | 528384/667270 [00:36<00:08, 17047.80it/s]

 80%|████████  | 534528/667270 [00:37<00:07, 17246.27it/s]

 81%|████████  | 540672/667270 [00:37<00:07, 17291.56it/s]

 82%|████████▏ | 546816/667270 [00:37<00:06, 17437.64it/s]

 83%|████████▎ | 552960/667270 [00:38<00:06, 17458.95it/s]

 84%|████████▍ | 559104/667270 [00:38<00:06, 17240.66it/s]

 85%|████████▍ | 565248/667270 [00:38<00:06, 16699.09it/s]

 86%|████████▌ | 571392/667270 [00:39<00:05, 17058.67it/s]

 87%|████████▋ | 577536/667270 [00:39<00:05, 16932.60it/s]

 87%|████████▋ | 583680/667270 [00:39<00:04, 17141.16it/s]

 88%|████████▊ | 589824/667270 [00:40<00:04, 17136.68it/s]

 89%|████████▉ | 595968/667270 [00:40<00:04, 17471.64it/s]

 90%|█████████ | 602112/667270 [00:41<00:03, 17237.30it/s]

 91%|█████████ | 608256/667270 [00:41<00:03, 17529.66it/s]

 92%|█████████▏| 614400/667270 [00:41<00:03, 17265.99it/s]

 93%|█████████▎| 620544/667270 [00:42<00:02, 17307.18it/s]

 94%|█████████▍| 626688/667270 [00:42<00:02, 17416.76it/s]

 95%|█████████▍| 632832/667270 [00:42<00:01, 17676.80it/s]

 96%|█████████▌| 638976/667270 [00:43<00:01, 17591.10it/s]

 97%|█████████▋| 645120/667270 [00:43<00:01, 17237.83it/s]

 98%|█████████▊| 651264/667270 [00:43<00:00, 17343.86it/s]

 99%|█████████▊| 657408/667270 [00:44<00:00, 17358.57it/s]

100%|██████████| 667270/667270 [00:44<00:00, 14934.19it/s]

### Insertion dans la base de donnée

In [ ]:
def insert_batches(index, pinecone_data, batch_size=256, max_workers=4):
    def insert_batch(batch):
        index.upsert(vectors=batch, show_progress=True)

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for i in range(0, len(pinecone_data), batch_size):
            batch = pinecone_data[i:i+batch_size]
            futures.append(executor.submit(insert_batch, batch))

In [ ]:
insert_batches(index, pinecone_data_parallel, batch_size=256, max_workers=16)

### Test de recherche

In [ ]:
query_text = "Qui est le plus grand voleur français ?"

In [ ]:
query_vector = embedding_model.encode([query_text], normalize_embeddings=True)

In [ ]:
results = index.query(
    vector=query_vector.astype("float32").tolist(),
    top_k=5,
    include_metadata=True
)

In [ ]:
print(results)

{'matches': [{'id': '119731',
              'metadata': {'entities': [],
                           'lang': 'fr',
                           'title': 'Français',
                           'year': ''},
              'score': 0.870938063,
              'values': []},
             {'id': '119608',
              'metadata': {'entities': [],
                           'lang': 'fr',
                           'title': 'Français',
                           'year': ''},
              'score': 0.870518923,
              'values': []},
             {'id': '119733',
              'metadata': {'entities': [],
                           'lang': 'fr',
                           'title': 'Français',
                           'year': ''},
              'score': 0.870498598,
              'values': []},
             {'id': '119447',
              'metadata': {'entities': ['ÉtatsUnis'],
                           'lang': 'fr',
                           'title': 'Français',
                           'year': ''},
              'score': 0.870167494,
              'values': []},
             {'id': '119523',
              'metadata': {'entities': [],
                           'lang': 'fr',
                           'title': 'Français',
                           'year': ''},
              'score': 0.868886,
              'values': []}],
 'namespace': '',
 'usage': {'read_units': 6}}

In [ ]:
for match in results["matches"]:
    doc_id = int(match["id"])
    print(df.iloc[doc_id]["text"])

De façon générale, le français demeure une des langues les plus enseignées dans le monde.
Le français est la deuxième langue la plus fréquemment utilisée dans les rencontres internationales.
Le français est enseigné de manière rudimentaire simples notions dorthographe et de grammaire
Le français est la deuxième langue la plus souvent enseignée en tant que langue étrangère à travers le monde, y compris aux ÉtatsUnis
Au long du , le français simpose comme langue scientifique et comme langue denseignement

## Récupération d'informations :

In [ ]:
basic_query = "Que s'est il passé lors de l'année 1956 en France ou dans le monde ?"

query_vector = embedding_model.encode([query_text], normalize_embeddings=True)

### Récupération des chunks les plus pertinents

In [ ]:
top_k_limit = 50

In [ ]:
results = index.query(
    vector=query_vector.astype("float32").tolist(),
    top_k=top_k_limit,
    include_metadata=True
)

### Première évaluation du retrieval

### Recherche sémantique
1. Utilisation de Milvus pour la recherche de vecteurs similaires
2. Récupération des chunks les plus pertinents (Top-k Retrieval)
3. Re-ranking des résultats
4. Hybrid Search (Combine recherche sémantique (vecteurs) et recherche classique (BM25).)
5. Traduction des résultats dans une langue demandé

## Génération de réponses :

### Query

### 1er retrival

### Reranking

### Génération de la réponse